### ISSUE TITLE
control 3.5.1 config.h not found

### ISSUE THREAD

**Issue by Schamschula** [gnu-octave/pkg-control#1]
While updating the MacPorts Portfile for octave-control to version 3.5.1 I ran into the following error:

> /usr/bin/clang++ -c -I/opt/local/include -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -fPIC -I/opt/local/include/octave-8.1.0/octave/.. -I/opt/local/include/octave-8.1.0/octave -I/opt/local/include  -pthread -pipe -Os -std=c++11 -stdlib=libc++ -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -arch arm64  -Wall -Wno-deprecated-declarations   __control_slicot_functions__.cc -o /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_octave_octave-control/octave-control/work/.tmp/oct-gZ0pv8.o
> In file included from __control_slicot_functions__.cc:1:
> In file included from ./sl_ab08nd.cc:31:
> ./common.h:59:10: fatal error: 'config.h' file not found
> #include "config.h"
>          ^~~~~~~~~~
> 1 error generated.
> make: *** [__control_slicot_functions__.oct] Error 1
> 
> pkg: error running 'make' for the control package

On further investigation, I noticed that there was a `config.h.in` file in version 3.5.0.

Note: this header file is also included by other source files.

**Comment by Schamschula** [comment]
I managed to build `octave-control` 3.5.1, by copying the `config.h.in` file from the previous version and adding `autoreconf` and `./configure` to the `Makefile`.

See: https://github.com/macports/macports-ports/commit/d3a7a34c797230fcdc93db69e428305863b87f7e

**Comment by ttl-octave** [comment]
The same file `config.h.in` is still included in `control-3.5.1.tar.gz` and also the `Makefile` did not change. Therefore I can not figure out what might be the problem.

**Comment by Schamschula** [comment]
Hmm. It sounds like I may be pulling the wrong source file. I'll have a look later today.

**Comment by Schamschula** [comment]
Sure enough. Setting up MacPorts to pull from the tag is easier than from releases. However, the tag tarball is incomplete.

I'll push a revision as a stealth update later (different checksums).

**Comment by Schamschula** [comment]
The octave port group was set up to pull from Sourceforge.

The shift to GitHub has caused me to use a number of combinations with the GitHub port group, as the naming convention is inconsistent (i.e. multiple GitHub accounts, etc.). However, the control package is the first time where the tag tarball wasn't fully usable.

P.S. I was talking about bumping the MacPorts revision number (from 0 to 1), not the package version number.

**Comment by Schamschula** [comment]
control 3.5.0 was pulled form Sourceforge, whereas control 3.5.1 from GitHub.

The port has been fixed: https://github.com/macports/macports-ports/commit/514cc548f067c7f5425b75fa89824198d80f2986
