### ISSUE TITLE
`mag2db` fails because `is_real_matrix` is undefined

### ISSUE THREAD

**Issue by tamaskenez** [gnu-octave/pkg-control#8]
Bugs and feature requests for GNU Octave including the packages are tracked on [Savannah](https://savannah.gnu.org/bugs/?group=octave). When browsing bugs, you can select *Octave Forge Package* as category and search for *(control)* in the summary. This should provide a list of reported bugs for the control package.

Running octave 9.3.0 and control 4.1.0 on MacOS, installed with MacPorts, I'm getting the following error for `mag2db`:

```
error: 'is_real_matrix' undefined near line 43, column 24
error: called from
    mag2db at line 43 column 19
```

Indeed, `is_real_matrix` doesn't seem like a valid Octave function, I think `isreal` should be called instead. But since `mag2db.m` and many other files here have been using `is_real_matrix` for many years, I'm not sure what the problem is.

**Comment by ttl-octave** [comment]
This works for me with Octave 9.3 and 10. Have you restarted Octave after installing the control package?

**Comment by tamaskenez** [comment]
Yes, and now I even tried to uninstall and reinstall octave + control and I still have the error.
I looked into the installed files for control and I see these files in the list:

```
  /opt/local/lib/octave/packages/control-4.1.0/aarch64-apple-darwin23.2.0-api-v59/PKG_ADD
  /opt/local/lib/octave/packages/control-4.1.0/aarch64-apple-darwin23.2.0-api-v59/__control_helper_functions__.oct
  /opt/local/lib/octave/packages/control-4.1.0/aarch64-apple-darwin23.2.0-api-v59/__control_slicot_functions__.oct
```

and if I manually execute this line from `PKG_ADD`:

```
autoload ("is_real_matrix", "/opt/local/lib/octave/packages/control-4.1.0/aarch64-apple-darwin23.2.0-api-v59/__control_helper_functions__.oct");
```

then `mag2db` works. Now I think this is a Macports installation problem, maybe the `PKG_LOAD` file should be under `/opt/local/share` instead.

Anyway, thanks for getting back to me, I'm closing this issue.
